paths:
  uploads: public/uploads
  static: public
  collections: content
  data: data
collections_config:
  data:
    path: data
    output: false
    icon: notes
    disable_add: true
    disable_add_folder: true
    disable_file_actions: false
  pages:
    path: content/pages
    output: true
    url: /[slug]
    icon: wysiwyg
    _enabled_editors:
      - visual
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: schemas/page.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        name: New Page
        icon: notes
  blog:
    path: content/posts
    output: true
    url: /blog/[slug]
    description: ''
    icon: notes
    _editables: {}
    _enabled_editors:
      - content
      - visual
    _inputs: {}
    _select_data: {}
    _structures: {}
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas:
      default:
        path: schemas/post.md
        reorder_inputs: true
        hide_extra_inputs: false
        remove_empty_inputs: false
        remove_extra_inputs: true
        icon: notes
        _editables: {}
        _inputs: {}
        _select_data: {}
        _structures: {}
  Medarbejder:
    path: content/medarbejder
    output: false
    url: /medarbejder/[slug]
    filter:
      base:
      include:
      exclude:
    parse_branch_index:
    name: Medarbjeder
    description: ''
    icon: 10k
    documentation:
    preview:
    sort:
    sort_options:
    singular_name:
    singular_key:
    _editables: {}
    _inputs: {}
    _select_data: {}
    _structures: {}
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas: {}
    schema_key:
_inputs:
  date:
    type: auto
    instance_value: now
    cascade: true
  title_suffix:
    type: auto
    comment: Added at the end of the title and highlighted in a different color
    cascade: true
  pagination.size:
    type: number
    cascade: true
  social:
    type: auto
    options:
      preview:
        icon: link
    cascade: true
  links:
    type: auto
    options:
      preview:
        icon: link
    cascade: true
  items:
    type: auto
    options:
      preview:
        icon: link
    cascade: true
  social[*].icon:
    type: select
    options:
      allow_empty: true
      values:
        - ph-facebook-logo
        - ph-instagram-logo
        - ph-twitter-logo
        - ph-github-logo
        - ph-youtube-logo
    cascade: true
  logo_url:
    type: auto
    comment: Link for the logo in the top left of the footer
    cascade: true
  copyright:
    type: auto
    comment: Automatically prefixed with the current year
    cascade: true
  isActive:
    type: switch
    cascade: true
  page_description:
    type: auto
    comment: Defaults to the description set in the Site SEO data file
    cascade: true
  favicon_icon:
    type: image
    comment: For the shortcut icon meta tag
    cascade: true
  faivcon_image:
    type: image
    comment: For the icon meta tag
    cascade: true
  canonical_url:
    type: auto
    comment: Defaults to the pages url
    cascade: true
  featured_image:
    type: auto
    comment: Defaults to the image set in the Site SEO data file
    cascade: true
  open_graph_type:
    type: auto
    comment: Defaults to the type 'website'
    cascade: true
  author_twitter_handle:
    type: auto
    comment: Defaults to the twitter site value set in the Site SEO data file
    cascade: true
  no_index:
    type: checkbox
    comment: >-
      When selected this removes the page from your sitemap and adds the noindex
      robots meta tag
    cascade: true
_select_data: {}
_structures:
  features:
    style: select
    values:
      - value:
          item:
          isActive:
_editables: {}
data_config: {}
timezone: Etc/UTC
